name: Skython

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"
    watchOS: "6.0"
    tvOS: "13.0"
    macOS: "10.15"

############
# fileGroups
############


############
# Configs
############

configs:
  Debug: debug
  Release: release
  Adhoc: release
  Beta: release

############
# Settings
############

settings:
  PRODUCT_BUNDLE_IDENTIFIER: $(AS_BUNDLE_IDENTIFIER)
